"""Incident report generation: prompt the LLM, parse, render Markdown + terminal.

The LLM is asked for four clearly-delimited sections (summary, root cause,
affected components, remediation). We parse those headers back out so we can
render both a clean Markdown artifact and a colored Rich terminal summary from
the same structured object.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .clustering import Cluster
from .llm import LLMProvider
from .summarize import build_context

_SYSTEM_PROMPT = (
    "You are an experienced site-reliability engineer performing incident "
    "triage. You are given clustered, ranked error signatures extracted from a "
    "log file. Produce a concise, actionable incident report. Be specific and "
    "avoid hedging. Use ONLY the exact section headers requested."
)

_SECTIONS = ("SUMMARY", "ROOT_CAUSE", "AFFECTED_COMPONENTS", "REMEDIATION")

_PROMPT_TEMPLATE = """\
Analyze the following ranked log error clusters and produce an incident report.

Respond using EXACTLY these four sections, each introduced by its header on its
own line (no other headers):

SUMMARY:
<one paragraph plain-language description of the incident>

ROOT_CAUSE:
<the single most likely root cause, with brief reasoning>

AFFECTED_COMPONENTS:
<bulleted list of affected services / components / subsystems>

REMEDIATION:
<numbered list of concrete, prioritized remediation steps>

--- LOG ERROR CLUSTERS (most severe first) ---
{context}
"""


@dataclass(frozen=True)
class IncidentReport:
    """Structured result of an LLM triage pass."""

    summary: str
    root_cause: str
    affected_components: str
    remediation: str
    provider: str
    model: str
    cluster_count: int
    total_errors: int
    generated_at: datetime
    raw: str

    def to_markdown(self, source: str) -> str:
        ts = self.generated_at.strftime("%Y-%m-%d %H:%M:%S")
        return (
            f"# Incident Report — {source}\n\n"
            f"*Generated by loglens on {ts} using {self.provider}/{self.model}.*\n\n"
            f"**Scope:** {self.total_errors} error/warning lines across "
            f"{self.cluster_count} distinct clusters.\n\n"
            f"## Summary\n\n{self.summary}\n\n"
            f"## Most Likely Root Cause\n\n{self.root_cause}\n\n"
            f"## Affected Components\n\n{self.affected_components}\n\n"
            f"## Remediation Steps\n\n{self.remediation}\n"
        )


def _parse_sections(raw: str) -> dict[str, str]:
    """Split the model output on the known section headers.

    Tolerant of markdown decoration (``**``, ``#``) and trailing colons the
    model may add around the headers.
    """

    pattern = re.compile(
        r"^[#*\s]*(" + "|".join(_SECTIONS) + r")\s*:?\s*$",
        re.IGNORECASE | re.MULTILINE,
    )
    matches = list(pattern.finditer(raw))
    result: dict[str, str] = {}
    for i, match in enumerate(matches):
        key = match.group(1).upper()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(raw)
        result[key] = raw[start:end].strip()
    return result


def generate_report(
    clusters: list[Cluster],
    provider: LLMProvider,
    source: str,
    redact: bool = False,
    token_budget: int = 6000,
) -> IncidentReport:
    """Run the full triage prompt and return a structured :class:`IncidentReport`."""

    context = build_context(clusters, provider, redact=redact, token_budget=token_budget)
    prompt = _PROMPT_TEMPLATE.format(context=context)
    raw = provider.generate(prompt, system=_SYSTEM_PROMPT)
    sections = _parse_sections(raw)

    # Fall back to the raw text in the summary slot if the model ignored the
    # header contract, so the user never loses the analysis.
    fallback = raw.strip()
    return IncidentReport(
        summary=sections.get("SUMMARY", fallback),
        root_cause=sections.get("ROOT_CAUSE", "(not provided by model)"),
        affected_components=sections.get("AFFECTED_COMPONENTS", "(not provided by model)"),
        remediation=sections.get("REMEDIATION", "(not provided by model)"),
        provider=provider.name,
        model=provider.model,
        cluster_count=len(clusters),
        total_errors=sum(c.count for c in clusters),
        generated_at=datetime.now(),
        raw=raw,
    )


def render_clusters_table(clusters: list[Cluster], console: Console) -> None:
    """Print a colored table of the top clusters to the terminal."""

    table = Table(title="Top error clusters", show_lines=False, expand=True)
    table.add_column("Severity", style="bold", no_wrap=True)
    table.add_column("Count", justify="right", no_wrap=True)
    table.add_column("Signature", overflow="fold")

    severity_color = {
        "CRITICAL": "bright_red",
        "ERROR": "red",
        "WARNING": "yellow",
        "NOTICE": "cyan",
        "INFO": "green",
    }
    for cluster in clusters:
        level = cluster.level.name if cluster.level else "UNKNOWN"
        color = severity_color.get(level, "white")
        table.add_row(
            f"[{color}]{level}[/{color}]",
            str(cluster.count),
            cluster.template[:160],
        )
    console.print(table)


def render_report(report: IncidentReport, console: Console) -> None:
    """Print the colored terminal incident summary."""

    console.print(
        Panel(
            report.summary,
            title="[bold]Incident Summary[/bold]",
            border_style="bright_red",
        )
    )
    console.print(
        Panel(
            report.root_cause,
            title="[bold]Most Likely Root Cause[/bold]",
            border_style="yellow",
        )
    )
    console.print(
        Panel(
            report.affected_components,
            title="[bold]Affected Components[/bold]",
            border_style="cyan",
        )
    )
    console.print(
        Panel(
            report.remediation,
            title="[bold]Remediation Steps[/bold]",
            border_style="green",
        )
    )
