"""Incident report generation: prompt the LLM, parse, render Markdown + terminal.

The LLM is asked for four clearly-delimited sections (summary, root cause,
affected components, remediation). We parse those headers back out so we can
render both a clean Markdown artifact and a colored Rich terminal summary from
the same structured object.
"""

from __future__ import annotations

import html
import json
import re
from dataclasses import dataclass
from datetime import datetime

from rich.console import Console
from rich.markup import escape
from rich.panel import Panel
from rich.table import Table

from .clustering import Cluster
from .llm import LLMProvider
from .summarize import build_context

_SYSTEM_PROMPT = (
    "You are an experienced site-reliability engineer performing incident "
    "triage. You are given clustered, ranked error signatures extracted from a "
    "log file. Produce a concise, actionable incident report. Be specific and "
    "avoid hedging. When a COMPUTED EVIDENCE block is present, treat its onset "
    "time, trigger, and cascade as ground truth and build your narrative around "
    "them. Use ONLY the exact section headers requested."
)

_SECTIONS = ("SUMMARY", "ROOT_CAUSE", "AFFECTED_COMPONENTS", "REMEDIATION")

_PROMPT_TEMPLATE = """\
Analyze the following ranked log error clusters and produce an incident report.

Respond using EXACTLY these four sections, each introduced by its header on its
own line (no other headers):

SUMMARY:
<one paragraph plain-language description of the incident>

ROOT_CAUSE:
<the single most likely root cause, with brief reasoning>

AFFECTED_COMPONENTS:
<bulleted list of affected services / components / subsystems>

REMEDIATION:
<numbered list of concrete, prioritized remediation steps>
{evidence}
--- LOG ERROR CLUSTERS (most severe first) ---
{context}
"""


@dataclass(frozen=True)
class IncidentReport:
    """Structured result of an LLM triage pass."""

    summary: str
    root_cause: str
    affected_components: str
    remediation: str
    provider: str
    model: str
    cluster_count: int
    total_errors: int
    generated_at: datetime
    raw: str

    def to_markdown(self, source: str) -> str:
        ts = self.generated_at.strftime("%Y-%m-%d %H:%M:%S")
        return (
            f"# Incident Report — {source}\n\n"
            f"*Generated by loglens on {ts} using {self.provider}/{self.model}.*\n\n"
            f"**Scope:** {self.total_errors} error/warning lines across "
            f"{self.cluster_count} distinct clusters.\n\n"
            f"## Summary\n\n{self.summary}\n\n"
            f"## Most Likely Root Cause\n\n{self.root_cause}\n\n"
            f"## Affected Components\n\n{self.affected_components}\n\n"
            f"## Remediation Steps\n\n{self.remediation}\n"
        )

    def to_dict(self, source: str) -> dict[str, object]:
        """A JSON-serializable view of the report for programmatic consumers."""

        return {
            "source": source,
            "generated_at": self.generated_at.isoformat(),
            "provider": self.provider,
            "model": self.model,
            "cluster_count": self.cluster_count,
            "total_errors": self.total_errors,
            "summary": self.summary,
            "root_cause": self.root_cause,
            "affected_components": self.affected_components,
            "remediation": self.remediation,
        }

    def to_json(self, source: str) -> str:
        """Pretty-printed JSON for piping into other tooling."""

        return json.dumps(self.to_dict(source), indent=2, ensure_ascii=False)

    def to_html(self, source: str) -> str:
        """A self-contained, styled HTML report (no external assets)."""

        ts = self.generated_at.strftime("%Y-%m-%d %H:%M:%S")

        def esc(text: str) -> str:
            return html.escape(text).replace("\n", "<br>")

        return _HTML_TEMPLATE.format(
            source=html.escape(source),
            ts=ts,
            provider=html.escape(self.provider),
            model=html.escape(self.model),
            total_errors=self.total_errors,
            cluster_count=self.cluster_count,
            summary=esc(self.summary),
            root_cause=esc(self.root_cause),
            affected=esc(self.affected_components),
            remediation=esc(self.remediation),
        )


_HTML_TEMPLATE = """\
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>loglens — incident report — {source}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 16px/1.6 -apple-system, Segoe UI, Roboto, sans-serif;
         max-width: 56rem; margin: 2rem auto; padding: 0 1.25rem; }}
  header {{ border-bottom: 2px solid #e11; padding-bottom: .75rem; margin-bottom: 1.5rem; }}
  h1 {{ font-size: 1.6rem; margin: 0 0 .25rem; }}
  .meta {{ color: #888; font-size: .85rem; }}
  .badges span {{ display: inline-block; background: #1118; color: #fff;
         border-radius: 999px; padding: .15rem .7rem; margin-right: .4rem; font-size: .8rem; }}
  section {{ margin: 1.25rem 0; padding: 1rem 1.25rem; border-radius: .6rem;
         background: #8881; border-left: 4px solid var(--c, #888); }}
  section h2 {{ font-size: 1rem; text-transform: uppercase; letter-spacing: .04em;
         margin: 0 0 .5rem; color: var(--c, #888); }}
  .summary {{ --c: #e11; }} .cause {{ --c: #e90; }}
  .affected {{ --c: #09c; }} .remediation {{ --c: #1a1; }}
</style>
</head>
<body>
<header>
  <h1>Incident Report — {source}</h1>
  <div class="meta">Generated by loglens on {ts} using {provider}/{model}.</div>
  <div class="badges"><span>{total_errors} error/warning lines</span>
       <span>{cluster_count} clusters</span></div>
</header>
<section class="summary"><h2>Summary</h2><p>{summary}</p></section>
<section class="cause"><h2>Most Likely Root Cause</h2><p>{root_cause}</p></section>
<section class="affected"><h2>Affected Components</h2><p>{affected}</p></section>
<section class="remediation"><h2>Remediation Steps</h2><p>{remediation}</p></section>
</body>
</html>
"""


def _parse_sections(raw: str) -> dict[str, str]:
    """Split the model output on the known section headers.

    Tolerant of markdown decoration (``**``, ``#``) and trailing colons the
    model may add around the headers.
    """

    pattern = re.compile(
        r"^[#*\s]*(" + "|".join(_SECTIONS) + r")\s*:?\s*$",
        re.IGNORECASE | re.MULTILINE,
    )
    matches = list(pattern.finditer(raw))
    result: dict[str, str] = {}
    for i, match in enumerate(matches):
        key = match.group(1).upper()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(raw)
        result[key] = raw[start:end].strip()
    return result


def generate_report(
    clusters: list[Cluster],
    provider: LLMProvider,
    source: str,
    redact: bool = False,
    token_budget: int = 6000,
    evidence: str | None = None,
) -> IncidentReport:
    """Run the full triage prompt and return a structured :class:`IncidentReport`.

    ``evidence`` is an optional block of deterministically-computed facts (onset,
    cascade, bursts) that grounds the model so it narrates over real analysis
    instead of guessing the timeline.
    """

    context = build_context(clusters, provider, redact=redact, token_budget=token_budget)
    evidence_section = f"\n{evidence}\n" if evidence else ""
    prompt = _PROMPT_TEMPLATE.format(context=context, evidence=evidence_section)
    raw = provider.generate(prompt, system=_SYSTEM_PROMPT)
    sections = _parse_sections(raw)

    # Fall back to the raw text in the summary slot if the model ignored the
    # header contract, so the user never loses the analysis.
    fallback = raw.strip()
    return IncidentReport(
        summary=sections.get("SUMMARY", fallback),
        root_cause=sections.get("ROOT_CAUSE", "(not provided by model)"),
        affected_components=sections.get("AFFECTED_COMPONENTS", "(not provided by model)"),
        remediation=sections.get("REMEDIATION", "(not provided by model)"),
        provider=provider.name,
        model=provider.model,
        cluster_count=len(clusters),
        total_errors=sum(c.count for c in clusters),
        generated_at=datetime.now(),
        raw=raw,
    )


def write_report(report: IncidentReport, path: str, source: str) -> str:
    """Write ``report`` to ``path``, choosing the format from the extension.

    ``.html`` → HTML, ``.json`` → JSON, anything else → Markdown. Returns the
    format name written so the caller can confirm it to the user.
    """

    lower = path.lower()
    if lower.endswith(".html") or lower.endswith(".htm"):
        content, fmt = report.to_html(source), "HTML"
    elif lower.endswith(".json"):
        content, fmt = report.to_json(source), "JSON"
    else:
        content, fmt = report.to_markdown(source), "Markdown"
    from pathlib import Path

    Path(path).write_text(content, encoding="utf-8")
    return fmt


def render_clusters_table(clusters: list[Cluster], console: Console) -> None:
    """Print a colored table of the top clusters to the terminal."""

    table = Table(title="Top error clusters", show_lines=False, expand=True)
    table.add_column("Severity", style="bold", no_wrap=True)
    table.add_column("Count", justify="right", no_wrap=True)
    table.add_column("Signature", overflow="fold")

    severity_color = {
        "CRITICAL": "bright_red",
        "ERROR": "red",
        "WARNING": "yellow",
        "NOTICE": "cyan",
        "INFO": "green",
    }
    for cluster in clusters:
        level = cluster.level.name if cluster.level else "UNKNOWN"
        color = severity_color.get(level, "white")
        table.add_row(
            f"[{color}]{level}[/{color}]",
            str(cluster.count),
            escape(cluster.template[:160]),
        )
    console.print(table)


def render_report(report: IncidentReport, console: Console) -> None:
    """Print the colored terminal incident summary."""

    # Escape model/analytics text so bracketed tokens like "[db]" render
    # literally instead of being parsed as Rich markup (and vanishing).
    console.print(
        Panel(
            escape(report.summary),
            title="[bold]Incident Summary[/bold]",
            border_style="bright_red",
        )
    )
    console.print(
        Panel(
            escape(report.root_cause),
            title="[bold]Most Likely Root Cause[/bold]",
            border_style="yellow",
        )
    )
    console.print(
        Panel(
            escape(report.affected_components),
            title="[bold]Affected Components[/bold]",
            border_style="cyan",
        )
    )
    console.print(
        Panel(
            escape(report.remediation),
            title="[bold]Remediation Steps[/bold]",
            border_style="green",
        )
    )
