{
 "title": "loglens — incident triage",
 "tags": [ "loglens" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Log volume by severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"loglens\", source=~\"$source\"} [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Total errors + criticals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({job=\"loglens\", source=~\"$source\", level=~\"error|critical\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Top error clusters (by signature)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(15, sum by (cluster, level) (count_over_time({job=\"loglens\", source=~\"$source\", level=~\"warning|error|critical\"} [$__range])))"
    }
   ]
  },
  {
   "title": "Error & critical log lines",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"loglens\", source=~\"$source\", level=~\"error|critical\"}"
    }
   ]
  }
 ]
}